language: objective-c
osx_image: xcode8.2

before_install:
    - brew update
    - brew install carthage
    - carthage update --platform ios

script:
    - xctool -project HakoBus.xcodeproj -scheme HakoBus -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

branches:
      only:
        - master
        - develop
