language: objective-c
osx_image: xcode8.2

before_install:
    - brew update
    - brew install carthage
    - carthage update --platform ios

script:
    - xcodebuild -scheme HakoBus -configuration Debug -sdk iphonesimulator -destination platform='iOS Simulator',OS='10.0',name='iPhone 7' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

branches:
      only:
        - master
        - develop
